### ISSUE TITLE
Bug: Odin Inspector 3 compatibility error

### ISSUE THREAD

**Issue by 949886** [handzlikchris/FastScriptReload#102]
I faced an error when I use FastScriptReload with OdinInspector 3:

`Library\PackageCache\com.handzlikchris.fastscriptreload@cc5dd52158\Scripts\Editor\NewFields\NewFieldsRendererDefaultEditorPatch.cs(34,141): error CS0103: The name 'DrawOdinInspector' does not exist in the current context`

- My Odin version: 3.1.14.3
- My Unity version: 2022.3.7

**Comment by mgmhunt** [comment]
Same issue. Moving the package from 
.../Library/PackageCache/com.handzlikchris.fastscriptreload@cc5dd52158
to 
.../Library/Packages

and commenting out 32-37 lines in the file
.../Library/Packages/com.handzlikchris.fastscriptreload@cc5dd52158/Scripts/Editor/NewFields/NewFieldsRendererDefaultEditorPatch.cs

will allow compile. not sure of the side effects of this..!

**Comment by handzlikchris** [comment]
shouldn't be much downside - it's editor for fields added at runtime. Without Odin it should still render normal fields

**Comment by Zarpyk** [comment]
> Source of Odin 3.1.14.3 in Sirenix.OdinInspector.Editor.dll:
> 
> ```cs
> /// <summary>Draws the default Odin inspector.</summary>
> public void DrawDefaultInspector() => this.DrawOdinInspector();
> 
> /// <summary>Draws the default Unity inspector.</summary>
> public void DrawUnityInspector() => base.DrawDefaultInspector();
> 
> private void DrawOdinInspector()
> {
>     ...
> }
> ```
> 
> maybe help.

Probably change line 35/36 to this fix it (I don't know what these methods do)?
```cs
var renderAdditionalFieldsDrawOdinInspectorPostfix = AccessTools.Method(typeof(NewFieldsRendererDefaultEditorPatch), nameof(DrawDefaultInspector));
var customOdinEditorRenderingMethod = AccessTools.Method("Sirenix.OdinInspector.Editor.OdinEditor:DrawDefaultInspector");
```

**Comment by GhatSmith** [comment]
My bad! Sorry guys for the issue, should be very easy to fix. [More details here](https://github.com/handzlikchris/FastScriptReload/issues/77#issuecomment-1786965409).

**Comment by handzlikchris** [comment]
Compile error as @GhatSmith mentioned, should be fixed with latest push, @949886 - feel free to reopen if still doesn't work after pulling latest
