### ISSUE TITLE
Why are all these Harmony and VR specify types being referenced?

### ISSUE THREAD

**Issue by jamesford42** [handzlikchris/FastScriptReload#105]
These using statements are in a lot of the files, and i don't know why, and i certainty don't want them as they make it not build.

using HarmonyLib;
using ImmersiveVRTools.Runtime.Common;
using ImmersiveVRTools.Runtime.Common.Extensions;
using ImmersiveVrToolsCommon.Runtime.Logging;

**Comment by handzlikchris** [comment]
FSR is editor only. It won't be included in your build. If you look at asm-definitions - they all target editor
