### ISSUE TITLE
Multiple precompiled assemblies with the same name System.Threading.Tasks.Extensions.dll

### ISSUE THREAD

**Issue by Mr-Ventures** [handzlikchris/FastScriptReload#109]
I just installed and now I get this error so I cannot play the game anymore.
Multiple precompiled assemblies with the same name System.Threading.Tasks.Extensions.dll
![image](https://github.com/handzlikchris/FastScriptReload/assets/46331598/24a44c4e-2aaa-4ed4-8576-212c4ff6c7f2)
Unity 2020.3.42f1 personal

**Comment by handzlikchris** [comment]
Unfortunately Unity doesn't have any great way of managing dll deps liek those.

You can change that lib to have some prefix like System.Threading.Tasks.Extensions-FSR.dll and adjust referecens.

I think the docs also suggest signing library? But I'm unsure how to go about that.
