### ISSUE TITLE
Fix record short syntax rewriting issue

### ISSUE THREAD

**Issue by builder-main** [handzlikchris/FastScriptReload#115]
Related to discussion in  #111 
I believe we could have a small patch that takes care of renaming records under the shortcut syntax with the missing _patched suffix.

**Comment by builder-main** [comment]
Actually the issue is witch the record keyword itself not specifically on the shortcut syntax of records.

**Comment by builder-main** [comment]
Also, tried to add a script override, for instance adding suffix `public record LeapAction__Patched_` but FSR still rewrites it `public record LeapAction`, the constructor gets rewritten with the suffix though : `public LeapAction__Patched_()`. We end up with the compiler throwing on the ctor `error CS1520: Method must have a return type'` as the ctor is recognised as a regular function.

**Comment by builder-main** [comment]
Alright, I think I got it, I post the workaround here and either I'll do a PR or someone else after further testing : 
Add in DynamicCompilationBase just before user Scripts overrides :
`root = new RecordeRewriter(DebugWriteRewriteReasonAsComment).Visit(root);`
Rewriter : 
```c#
using FastScriptReload.Runtime;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace FastScriptReload.Editor.Compilation.CodeRewriting
{
	class RecordeRewriter : FastScriptReloadCodeRewriterBase
        {
	        public RecordeRewriter(bool writeRewriteReasonAsComment)
				: base(writeRewriteReasonAsComment)
	        {
		        }
	        
	        public override SyntaxNode VisitRecordDeclaration(RecordDeclarationSyntax node)
	        {
		        return AdjustRecordName(node, node.Identifier);
	        }

	        private SyntaxNode AdjustRecordName(RecordDeclarationSyntax node, SyntaxToken nodeIdentifier)
	        {
		        var typeName = nodeIdentifier.ToString(); //Not ToFullString() as it may include spaces and break.
		        
		        if (!typeName.EndsWith(AssemblyChangesLoader.ClassnamePatchedPostfix))
		        {
			        typeName += AssemblyChangesLoader.ClassnamePatchedPostfix;
		        }

		        return AddRewriteCommentIfNeeded(
			        node.ReplaceToken(nodeIdentifier, SyntaxFactory.Identifier(typeName)), 
			        $"{nameof(RecordeRewriter)}:{nameof(AdjustRecordName)}"
			    );
	        }
        }
}
```

**Comment by handzlikchris** [comment]
Thanks - that looks good, and targetting just `VisitRecordDeclaration` makes it quite isolated. It'd be great if you can create a PR and I'll merge that in
