### ISSUE TITLE
FileWatcherImplementation does not contain a definition for DirectWindowsApi

### ISSUE THREAD

**Issue by Toernblom** [handzlikchris/FastScriptReload#118]
Hey, on Ubuntu 22.04, Unity 2023.2.5f1.

When importing through .git url i get this error.
Found a previous closed issue regarding the FileWatcher but couldn't quite understand
if this is related to that or not..

Library/PackageCache/com.handzlikchris.fastscriptreload@6412e8454a/Scripts/Editor/FastScriptReloadManager.cs(160,48): error CS0117: 'FileWatcherImplementation' does not contain a definition for 'DirectWindowsApi'

**Comment by FREEZX** [comment]
Getting the same issue in our gameci docker instance.

**Comment by handzlikchris** [comment]
likely same, feel free to comment out that part for now - I'll patch it. DirectWindowsApi will have `#if Windows` - likelt that's why it fails to compile on other platform. It's not needed - commenting it out shouldn't affect functionality

**Comment by aklaiber** [comment]
:+1:
