### ISSUE TITLE
UI Toolkit support?

### ISSUE THREAD

**Issue by LiamKarlMitchell** [handzlikchris/FastScriptReload#144]
Live reload for UI Toolkit?
uxml
uss

Whilst there is Live Reload feature built into Unity.
It seems to require focusing the Unity Editor.
That sucks.

When I trigger Refresh Unity Assets action from Rider, it does reload the UI changes, so it should be possible to detect these changes and trigger reloading of the UI Toolkit assets that have changed?

**Comment by handzlikchris** [comment]
I've never checked UI Toolkit. Not 100% sure how UI Toolkit works under the hood.

FSR will only reload scripts - I've got a feeling that with markup language - scripts might not be that much involved and instead the markup is reloaded and rebuild.

If you have a small project with example of what you'd like reloaded - I can have a look

**Comment by handzlikchris** [comment]
I'll close it as there's no action on this one - feel free to post again if you got a repro
