### ISSUE TITLE
Update Roslyn libs to latest (there are some bugs that have source at Roslyn not properly interpreting code)

### ISSUE THREAD

**Issue by handzlikchris** [handzlikchris/FastScriptReload#22]
Linked #23

**Comment by SamPruden** [comment]
What version of Roslyn is it actually using at the moment? I couldn't find a very easy way to check (I'm probably being thick, there) but it appears **very** out of date. It seems to be from before a lot of modern C# syntax, such as `new()`, local functions, and switch expressions. At least, I think that's what's happening in #84. It appears to be around C#6 or C#7?

IMO this is an urgent fix. This is responsible for the majority of problem's I'm having with FSR, as my code base uses those features extensively.

I may look at a PR if I get an opportunity, as I'll likely need to get this fixed myself locally.

**Comment by SamPruden** [comment]
Are you accepting PRs on this? I assume not - randoms adding binaries is probably a bad idea!

**Comment by handzlikchris** [comment]
yep - added, checked CRC with nuget 4.6.0 - all ok.

Only issue being older Unity versions doesn't play well with that. We've ended up with 2 sets of dll for now that'll be used depending on editor used.

Thanks!

**Comment by handzlikchris** [comment]
#96 #86
