### ISSUE TITLE
Install as a UPM package?

### ISSUE THREAD

**Issue by laicasaane** [handzlikchris/FastScriptReload#3]
I want to try this out, but the plugin doesn't conform to UPM format. Could you please make changes so that we can easily install it as a UPM package?

And since the license is MIT, we can also register the package on [OpenUPM](https://openupm.com/packages/) for better accessibility.

**Comment by handzlikchris** [comment]
Sure - it's first thing on the dev list

**Comment by handzlikchris** [comment]
#53

**Comment by laicasaane** [comment]
The package name should conform to reverse domain name notation with at least 3 components.

For example:

```
"name": "com.handzlikchris.fastscriptreload",
```

**Comment by handzlikchris** [comment]
thanks - I'll check it out

**Comment by SyaoranChang** [comment]
Hi,
Can I use this method to install now?

**Comment by handzlikchris** [comment]
Hi, sure - `You can also install via package manager. Window -> Package Manager -> + -> Add package from Git url: https://github.com/handzlikchris/FastScriptReload.git?path=Assets`

**Comment by SyaoranChang** [comment]
Thanks for the reply.
I have seen this method from README.
But after using Git via package manager.
It will become the all team members need to install Git to download, but no need via OpenUPM.

**Comment by handzlikchris** [comment]
alright - for this one I think prority was to add Package Manager support - I though that's same as UPM package and that Unity handles download for you.

Are you saying that Unity depends on git executable for that functionality?

I've got little OpenUPM experience and now that it works with Package Manager the priority for that story will be quite low.

Happy to accept PR for that if it's something that could be useful to community

**Comment by laicasaane** [comment]
@handzlikchris I've taken the liberty to submit this package to OpenUPM. It's live now. However, your latest `package.json` and your release tag are mismatched, and because you was releasing tags that didn't adhere to semver convention OpenUPM can't distribute those tags.

The immediate action is increasing your version to `1.6.1` and release a tag with that exact version string and OpenUPM will handle things automatically. Cheers!

https://openupm.com/packages/com.handzlikchris.fastscriptreload/

**Comment by handzlikchris** [comment]
Nice, thanks - just pushed the updated now

**Comment by SyaoranChang** [comment]
1.> Are you saying that Unity depends on git executable for that functionality?

If there is no installation of Git to open a project, there will be this error message.
"An error occurred while resolving packages:
  Project has invalid dependencies:
    com.handzlikchris.fastscriptreload: No 'git' executable was found. 
Please install Git on your system then restart Unity and Unity Hub"

![Snipaste_2023-11-27_13-44-41](https://github.com/handzlikchris/FastScriptReload/assets/18550228/327a4694-4ec9-4221-8f54-6806255081ff)

2.Thanks for adding the installation via OpenUPM, now I can install it using this command.
openupm add com.handzlikchris.fastscriptreload
​
3.There seems to be an issue with Git via package manager, check for updates and then display the update button.
I try Git url to install, the button will always be displayed even when there is no update.
![Snipaste_2023-11-27_13-58-25](https://github.com/handzlikchris/FastScriptReload/assets/18550228/7df3ef04-4a72-4820-993a-18d3fcf7fb3a)

I try OpenUPM to install, There is no display button when there is no update.
![Snipaste_2023-11-27_14-03-02](https://github.com/handzlikchris/FastScriptReload/assets/18550228/3a60259a-7055-4201-bc4c-42dd6945a704)
