### ISSUE TITLE
Clarify behaviour when using the plugin outside of play mode

### ISSUE THREAD

**Issue by joonjoonjoon** [handzlikchris/FastScriptReload#59]
I'm not particularly looking for the code hotloading this plugin seems to be focused on, but I'm curious if there's a way I Can use it in my normal workflow to speed up compilation. It seems like it does do anything if not used while the editor is in play mode, but reading the documentation I'm not sure if that's intended/expected or if it is broken.

**Comment by handzlikchris** [comment]
It's intended to work this way. If you want to use experimental in-editor workflow you can turn it of from Fast Script Reload welcome / settings screen
