### ISSUE TITLE
Error on import: 'DynamicMethod' could not be found

### ISSUE THREAD

**Issue by equizo** [handzlikchris/FastScriptReload#69]
FSR 1.5
Unity 2020.3.27

`Library\PackageCache\com.handzlikchris.fastscriptreload@5f73a1ba43\Scripts\Runtime\AssemblyChangesLoader.cs(189,57): error CS0246: The type or namespace name 'DynamicMethod' could not be found (are you missing a using directive or an assembly reference?) `

**Comment by handzlikchris** [comment]
what backend are you on .Net/NetStandard?

**Comment by equizo** [comment]
> what backend are you on .Net/NetStandard?

Mono, .Net Standard 2.0

**Comment by spireggs** [comment]
Same error.  Unity Ver: 2020.3.37f1
.Net Standard 2.0

**Comment by git-mingfei** [comment]
me too

**Comment by handzlikchris** [comment]
thanks - looks like DynamicMethod could not be resolved in some versions, this will get it running
https://github.com/handzlikchris/FastScriptReload/commit/ea204caaf780890a692a7053bb2f1fff518a105a

You can pull via package manager using specific commit-id
