### ISSUE TITLE
Request : Odin Inspector compatibility for New Fields

### ISSUE THREAD

**Issue by GhatSmith** [handzlikchris/FastScriptReload#77]
Right now, when the project is using Odin Inspector, you have to switch inspector to Debug mode to see the [FSR] Dynamically Added Fields. Would be great if there was a direct compatibility with Odin Inspector, without having to use debug mode.

**Comment by handzlikchris** [comment]
I've got a feeling Odin will replace Default inspector, FSR is hooking into it via `FastScriptReload.Editor.NewFields.NewFieldsRendererDefaultEditorPatch.NewFieldsRendererDefaultEditorPatch`

Probably as simple as changing Patch target from default inspector to Odin one.

If you know which one would that be then I'll be simpler to put in

**Comment by GhatSmith** [comment]
I made this fix, and it seems to work. Feel free to include it officially!
**Caution**: I'm using Odin v2, so I've not tested on the last Odin version (v3), but it should work I think.

Code at the end of the NewFieldsRendererDefaultEditorPatch static constructor:
```
#if ODIN_INSPECTOR
                var renderAdditionalFieldsDrawOdinInspectorPostfix = AccessTools.Method(typeof(NewFieldsRendererDefaultEditorPatch), nameof(DrawOdinInspector));
                var customOdinEditorRenderingMethod = AccessTools.Method("Sirenix.OdinInspector.Editor.OdinEditor:DrawOdinInspector");
                harmony.Patch(customOdinEditorRenderingMethod, postfix: new HarmonyMethod(renderAdditionalFieldsDrawOdinInspectorPostfix));
#endif
```

Method added to the class: NewFieldsRendererDefaultEditorPatch
```
private static void DrawOdinInspector(UnityEditor.Editor __instance)
{
    RenderNewlyAddedFields(__instance);
}
```

**Comment by handzlikchris** [comment]
nice one, thanks - if you could PR - that'd be great. Otherwise I'll try to put it in with other changes

**Comment by GhatSmith** [comment]
Included in my [pull request](https://github.com/handzlikchris/FastScriptReload/pull/80).

**Comment by builder-main** [comment]
@GhatSmith  https://github.com/handzlikchris/FastScriptReload/pull/80#issuecomment-1784966841
Could I have your feedback on this ? Thanks for trying to add this, I'm on Odin 3 however.

**Comment by GhatSmith** [comment]
> @GhatSmith [#80 (comment)](https://github.com/handzlikchris/FastScriptReload/pull/80#issuecomment-1784966841) Could I have your feedback on this ? Thanks for trying to add this, I'm on Odin 3 however.

Just had a look, my bad I forgot to add something in my initial pull request...
@handzlikchris could you add the missing DrawOdinInspector method inside your NewFieldsRendererDefaultEditorPatch class please, so the nameof is working properly.

```
#if ODIN_INSPECTOR
        private static void DrawOdinInspector(UnityEditor.Editor __instance)
        {
            RenderNewlyAddedFields(__instance);
        }
#endif
```

By the way I tested with latest Odin version (v3.1.14.3) and it was working.

**Comment by handzlikchris** [comment]
thanks - that's added

**Comment by nick-s5** [comment]
The DrawOdinInspector method is missing in the current Asset Store version

**Comment by OikoumE** [comment]
just installed fast script reload 1.6.1 on unity 2022.3.17f1 and im getting this error:
```Assets\FastScriptReload\Scripts\Editor\NewFields\NewFieldsRendererDefaultEditorPatch.cs(34,141): error CS0103: The name 'DrawOdinInspector' does not exist in the current context
```
even after installing oding (3.2.1.0 inspector+serializer) error persists

**Comment by handzlikchris** [comment]
you can try pull github version - tere's was an update that addesses it
https://github.com/handzlikchris/FastScriptReload/commit/260169c8914fa36470843cc1f950a50a725c4ef6
