### ISSUE TITLE
Is this warning ok ?

### ISSUE THREAD

**Issue by nicoszpako** [handzlikchris/FastScriptReload#94]
Hello, I use FSR with Unity 2022.3.4f1, and when I reload a Script everything works but I get this warning : 

`FSR: Unable to create assembly with 'InternalsVisibleToAttribute' for dynamically recompiled code. Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
`
Is it harmless ? 
Thanks a lot for your work though, it's really amazing.

**Comment by handzlikchris** [comment]
Thanks, glad you like it. Yes it's harmless.

Happens for stuff like Rider integration assy.

I'll hide it behind debug for firther release as ot's generally not that
important.

**Comment by acornellier** [comment]
I get this error whenever I make any change, so it's a little annoying.
Could you change the log level please?
